version: '3.3'
services:
  mongo_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    # build: ./ui
    image: ${USER_NAME}/ui:${UI_VER}
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
      - back_net
  post:
    # build: ./post-py
    image: ${USER_NAME}/post:${POST_VER}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - mongo_db
    ports:
      - "5000:5000"
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: service.post
    networks:
      - back_net
  comment:
    # build: ./comment
    image: ${USER_NAME}/comment:${COMMENT_VER}
    networks:
      - back_net
  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - back_net
  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - back_net
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secretpass
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - front_net
      - back_net
  alertmanager:
    image: ${USER_NAME}/alertmanager
    # command:
    #   - '-config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - front_net
      - back_net
volumes:
  post_db:
  grafana_data:

networks:
  front_net:
  back_net:
